### ISSUE TITLE
Missing multiple_comp.txt file

### ISSUE THREAD

**Issue by mfurla** [DepledgeLab/DRUMMER#21]
Dear developers,

I'm running DRUMMER on a dataset, but the multiple_comp.txt file is missing. 

For each chromosome, I get a set of comparison directories and the corresponding summary.txt files, however, the final aggregation step doesn't seem to work.

Do you know what may have caused this issue?

Thanks in advance,

Mattia

**Comment by JonAbebe** [comment]
Hi Mattia,

Sorry for the delayed response. I would need a little more information to help.
Does DRUMMER return an error message? 
Also, maybe you can provide the first few lines of the summary.txt files so I can investigate further.

Thanks,

Jonathan

**Comment by mfurla** [comment]
Hi Jonathan,

thank you very much for your kind response.

1) DRUMMER does not return any error.
2) Regarding the Summary file, since there are several comparisons involved in the analysis, I thought it would be easier to share with you the entire result folder for one chromosome.

You can find it here (temporary link): https://filesender.garr.it/?s=download&token=a736e810-7204-4287-8e57-01676105e40e

Thank you again for your help!

Cheers.

Mattia

**Comment by JonAbebe** [comment]
Hi Mattia,

So I took some time to dig into this issue with the data you provided me. The issue seems to be from what columns this script expects and what is provided. When I initially wrote this script the testing was done on m6A data - thus this script expects the column 'nearest_ac_motif' in the columns. However, from your data, it looks like you are not interested in m6A so you do not use the flag "-m".

For the time being, I suggest attempting to set the "-m" flag as True. This should force the multiple_comp.txt file to be generated, and then you can simply ignore/delete the columns pertaining m6A modifications in the output. 

Will attempt to address this bug in the coming days - thanks for bringing it up. Let me know if the suggestion above does not work and then we can go from there.

Jonathan

**Comment by mfurla** [comment]
Hi Jonathan,

thank you for your help!

I run drummer with the -m flag and I got the multiple_comp.txt file! Unfortunately, it worked only for the first chromosome.

I run your tool chromosome by chromosome in a for loop, I don't know if this is relevant...

while read -r line; 
do
    python3 DRUMMER.py -r genome.fasta \
        -t minimap.sortG.2.bam \
        -c minimap.sortG.1.bam \
        -o /resultsFolder/$line/ \
        -a exome \
        -p 0.05 \
        -n $line ;
done < chromosomes.txt || true

Thank you again!

Mattia

**Comment by JonAbebe** [comment]
Hi Mattia,

To be clear, the runs are completing for each chromosome but failing to create a unified multiple_comp.txt?

**Comment by mfurla** [comment]
Hi Jon,

the tool produced a folder for each chromosome. Within these folders, there are many sub-folder containing the comparisons of each treated sample to each control sample (9 folders since I have 3 control replicates and 3 treated replicates). Within these folders, there are the expected _chrXY.complete.txt_ files.

I also expected a _multiple_comp.txt_ file for each chromosome, however, I got one only for chr01.

In [trees.txt](https://github.com/DepledgeLab/DRUMMER/files/10022733/trees.txt), you can find the trees of the result folders for chr01 and chr02.

Mattia

**Comment by JonAbebe** [comment]
Hi Mattia,

Honestly, I would have no idea where to begin debugging this issue without some error message or access to the data.
But here is an alternative. Since the multiple_comp is generated at the last step - let us just use this to generate the file directly.
By that I mean, you can directly use the multiple_combine.py script from the modules folder to generate a multiple_comp.txt for each directory. Below is an example of how you would do it for chr1. All you really need is the directory name, the names of the individual folders, and some output location. Since the individual folders should be consistent for all chromosomes, using a for loop should be simple.

python3 multiple_combine.py -d chr01 -o _output_ -c inimap.sortG.1.1-inimap.sortG.2.1 inimap.sortG.1.1-inimap.sortG.2.2 inimap.sortG.1.1-inimap.sortG.2.3 inimap.sortG.1.2-inimap.sortG.2.1 inimap.sortG.1.2-inimap.sortG.2.2 inimap.sortG.1.2-inimap.sortG.2.3 inimap.sortG.1.3-inimap.sortG.2.1 inimap.sortG.1.3-inimap.sortG.2.2 inimap.sortG.1.3-inimap.sortG.2.3 

Let me know if that works for you,

Jonathan

Edited for grammar.

**Comment by mfurla** [comment]
Dear Jonathan,

thank you very much for your suggestion, unfortunately, the routine works for chr01 but not for the other chromosomes.

For some reason the function _get_highest_gtest_ works with chr01, but for all the other chromosomes it fails.

Specifically, for the very same _lst_rep_dir_ (['inimap.sortG.1.1-inimap.sortG.2.1', 'inimap.sortG.1.1-inimap.sortG.2.2', 'inimap.sortG.1.1-inimap.sortG.2.3', 'inimap.sortG.1.2-inimap.sortG.2.1', 'inimap.sortG.1.2-inimap.sortG.2.2', 'inimap.sortG.1.2-inimap.sortG.2.3', 'inimap.sortG.1.3-inimap.sortG.2.1', 'inimap.sortG.1.3-inimap.sortG.2.2', 'inimap.sortG.1.3-inimap.sortG.2.3']), if I set **outputdir='/path/to/chr01'** I manage to compute the combined_df and to complete the main of multiple_combine.py. However, If I set **outputdir='/path/to/chr02'** when I try to compute the combined_df I get the following error:

**combined_df,index_replicates,final_dict = get_highest_gtest(df,suffix_list,m6A)**
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'eleven_bp_motif.9'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 16, in get_highest_gtest
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/series.py", line 958, in __getitem__
    return self._get_value(key)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/series.py", line 1069, in _get_value
    loc = self.index.get_loc(label)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'eleven_bp_motif.9'

I hope this can help for the debug.

Since it looks like you just need the summary files to execute multiple_combine.py, in this archive you can find the summaries for chr01 and chr02: [chrSummaries.tar.gz](https://github.com/DepledgeLab/DRUMMER/files/10032608/chrSummaries.tar.gz)

Thank you again and best regards,

Mattia
