### ISSUE TITLE
Dangerous default settings; using all CPUs

### ISSUE THREAD

**Issue by BradBalderson** [DepledgeLab/DRUMMER#22]
Dear Drummer developers,

Thankyou very much for developing a very useful tool. 

I find the default settings automatically use 100% CPU and it's unclear how to set the number of CPUs used.

Could an option be added to set the number of CPUs, and the default set to 1 CPU, so my sys-admin does not boot me off our servers? 

Kind regards

**Comment by JonAbebe** [comment]
Hello,

Thank you for the kind words. 
We incorporated multiprocessing to bypass the global interpreter lock so we may run the analysis of multiple transcripts (isoform mode) or multiple replicates (exome mode) in parallel. However, I can see how this can cause issues.

I agree, a potential solution is to set a hard cap on the number processes DRUMMER uses. 

Since it may take time for me to test DRUMMER with this new capabilities, maybe you can change the code in your local copy? 

If you go into the modules/test_isoform.py file, at line 193, change 
with concurrent.futures.ProcessPoolExecutor() as executor: 
with concurrent.futures.ProcessPoolExecutor(**max_workers=1**) as executor:

Similarly, in modules/test_exome.py file, at line 187, change:
with concurrent.futures.ProcessPoolExecutor() as executor: 
with concurrent.futures.ProcessPoolExecutor(**max_workers=1**) as executor:

Let me know if this works for you, will update DRUMMER in the coming days.

Jonathan

**Comment by BradBalderson** [comment]
Awesome, thankyou very much for this advice, and appreciate how much work it takes for long term package maintenance. Will set it and let you know how it goes!

**Comment by BradBalderson** [comment]
Have removed the multithreading for now, thanks again for advice!
